// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyAbroadApi.Data;

#nullable disable

namespace StudyAbroadApi.Data
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610041312_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("StudyAbroadApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("GPA")
                        .HasColumnType("REAL");

                    b.Property<string>("HighSchool")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SATScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudyAbroadApi.Models.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcceptanceRate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MinGPA")
                        .HasColumnType("REAL");

                    b.Property<int>("MinSAT")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Universities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcceptanceRate = "4%",
                            Major = "Engineering, Computer Science",
                            MinGPA = 3.8999999999999999,
                            MinSAT = 1500,
                            Name = "MIT",
                            State = "Massachusetts",
                            Tier = "Ivy+"
                        },
                        new
                        {
                            Id = 2,
                            AcceptanceRate = "4%",
                            Major = "Technology, Business",
                            MinGPA = 3.8999999999999999,
                            MinSAT = 1500,
                            Name = "Stanford University",
                            State = "California",
                            Tier = "Ivy+"
                        },
                        new
                        {
                            Id = 3,
                            AcceptanceRate = "5%",
                            Major = "Liberal Arts, Law, Medicine",
                            MinGPA = 3.8999999999999999,
                            MinSAT = 1500,
                            Name = "Harvard University",
                            State = "Massachusetts",
                            Tier = "Ivy+"
                        },
                        new
                        {
                            Id = 4,
                            AcceptanceRate = "14%",
                            Major = "Engineering, Business",
                            MinGPA = 3.7000000000000002,
                            MinSAT = 1400,
                            Name = "UC Berkeley",
                            State = "California",
                            Tier = "Top 20"
                        },
                        new
                        {
                            Id = 5,
                            AcceptanceRate = "17%",
                            Major = "Engineering, Business",
                            MinGPA = 3.7000000000000002,
                            MinSAT = 1360,
                            Name = "University of Michigan",
                            State = "Michigan",
                            Tier = "Top 20"
                        },
                        new
                        {
                            Id = 6,
                            AcceptanceRate = "21%",
                            Major = "Business, Arts, Law",
                            MinGPA = 3.6000000000000001,
                            MinSAT = 1350,
                            Name = "NYU",
                            State = "New York",
                            Tier = "Top 30"
                        },
                        new
                        {
                            Id = 7,
                            AcceptanceRate = "31%",
                            Major = "Engineering, Business",
                            MinGPA = 3.5,
                            MinSAT = 1300,
                            Name = "University of Texas at Austin",
                            State = "Texas",
                            Tier = "Top 50"
                        },
                        new
                        {
                            Id = 8,
                            AcceptanceRate = "49%",
                            Major = "Engineering, Agriculture",
                            MinGPA = 3.2999999999999998,
                            MinSAT = 1250,
                            Name = "Purdue University",
                            State = "Indiana",
                            Tier = "Top 50"
                        },
                        new
                        {
                            Id = 9,
                            AcceptanceRate = "64%",
                            Major = "Business, Engineering, Journalism",
                            MinGPA = 3.0,
                            MinSAT = 1150,
                            Name = "Arizona State University",
                            State = "Arizona",
                            Tier = "Top 100"
                        },
                        new
                        {
                            Id = 10,
                            AcceptanceRate = "41%",
                            Major = "Engineering, Business, Hospitality",
                            MinGPA = 3.0,
                            MinSAT = 1160,
                            Name = "University of Central Florida",
                            State = "Florida",
                            Tier = "Top 100"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
